import type { Application } from '@/lib/types';

export const initialApplications: Application[] = [
  {
    id: '1',
    company: 'Innovate Inc.',
    position: 'Frontend Developer',
    dateApplied: new Date('2024-07-15'),
    status: 'interviewed',
    linkToJobPosting: 'https://example.com/job/1',
    notes: 'First interview with hiring manager went well. Second technical interview scheduled for next week.',
    interviewDate: new Date('2024-07-22'),
  },
  {
    id: '2',
    company: 'Data Dynamics',
    position: 'Data Scientist',
    dateApplied: new Date('2024-07-12'),
    status: 'applied',
    linkToJobPosting: 'https://example.com/job/2',
    notes: 'Applied through LinkedIn. Followed up with an email to the recruiter.',
  },
  {
    id: '3',
    company: 'Creative Solutions',
    position: 'UI/UX Designer',
    dateApplied: new Date('2024-07-10'),
    status: 'offer',
    linkToJobPosting: 'https://example.com/job/3',
    notes: 'Completed the design challenge. Received positive feedback. They sent an offer!',
    interviewDate: new Date('2024-07-18'),
    offerDate: new Date('2024-07-25'),
  },
  {
    id: '4',
    company: 'Secure Systems',
    position: 'Cybersecurity Analyst',
    dateApplied: new Date('2024-07-05'),
    status: 'rejected',
    linkToJobPosting: 'https://example.com/job/4',
    notes: 'Had a promising interview, but they decided to go with a candidate with more experience in cloud security.',
    interviewDate: new Date('2024-07-11'),
    rejectionDate: new Date('2024-07-19'),
  },
  {
    id: '5',
    company: 'Mobile First',
    position: 'iOS Developer',
    dateApplied: new Date('2024-06-28'),
    status: 'rejected',
    linkToJobPosting: 'https://example.com/job/5',
    notes: 'Did not pass the initial screening.',
    rejectionDate: new Date('2024-07-02'),
  },
  {
    id: '6',
    company: 'Innovate Inc.',
    position: 'Backend Developer',
    dateApplied: new Date('2024-07-20'),
    status: 'applied',
    linkToJobPosting: 'https://example.com/job/6',
    notes: 'Saw this role posted on their company website, seems like a good fit for my skills.',
  },
];
